default:
  image: node:20.13.1-alpine

tags:
  - ppj

stages:
  - build
  # - dockerize
  # - deploy

build:
  stage: build
  script:
    - npm install -f
    - yarn build

# dockerize:
#   image: docker:20.10-dind

